name: Testes

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  testes:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Instalar o Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Rodar os testes
        run: ./mvnw test